site_name: "rustus"
site_url: "https://s3rius.github.io/rustus"
repo_url: https://github.com/s3rius/rustus
repo_name: s3rius/rustus
edit_uri: ""

theme:
  icon:
    repo: fontawesome/brands/github
  logo: imgs/logo_horizontal.svg
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - search.suggest
    - header.autohide
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon:  material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search:
      lang: en


extra:
  generator: true

markdown_extensions:
  - admonition
  - markdown.extensions.meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true