apiVersion: v2
name: rustus
description: A Helm chart for rustus
home: https://github.com/s3rius/rustus/
icon: https://raw.githubusercontent.com/s3rius/rustus/master/imgs/logo.svg
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.2.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.4.8"


dependencies:
  - name: redis
    version: ^16.0
    condition: redis.enabled
    repository: "https://charts.bitnami.com/bitnami"
  - name: postgresql
    version: ^11.0
    condition: postgresql.enabled
    repository: "https://charts.bitnami.com/bitnami"
  - name: mysql
    version: ^8.0
    condition: mysql.enabled
    repository: "https://charts.bitnami.com/bitnami"